#!/usr/bin/env bash
rm -rf foobar
rm -rf minecraft
rm -rf dhcp
rm -rf dhcp-dns
rm -rf htpasswd-file
rm -rf mailboxes
rm -rf sshd
rm -rf itsecur-firewall
rm -rf tcpwrappers
rm -rf nis
rm -rf adsl-client
rm -rf apache
rm -rf bind8
rm -rf buner
rm -rf pserver
rm -rf quota
rm -rf dovecot
rm -rf fail2ban
rm -rf fetchmail
rm -rf firewalld
rm -rf frox
rm -rf grub
rm -rf idmapd
rm -rf ipsec
rm -rf iscsi-client
rm -rf iscsi-server
rm -rf iscsi-target
rm -rf iscsi-tgtd
rm -rf jabber
rm -rf krb5
rm -rf ldap-client
rm -rf ldap-server
rm -rf ldap-useradmin
rm -rf raid
rm -rf lvm
rm -rf majordomo
rm -rf mon
rm -rf mysql
rm -rf xinetd
rm -rf inetd
rm -rf exports
rm -rf exports-nfs4
rm -rf openslp
rm -rf phpini
rm -rf postfix
rm -rf postgresql
rm -rf pap
rm -rf ppp-client
rm -rf pptp-client
rm -rf pptp-server
rm -rf procmail
rm -rf proftpd
rm -rf qmailadmin
rm -rf samba
rm -rf at
rm -rf sentry
rm -rf sendmail
rm -rf smart-status
rm -rf spam
rm -rf squid
rm -rf sarg
rm -rf telnet
rm -rf st
rm -rf stunnel
rm -rf syslog-ng
rm -rf vgetty
rm -rf webalizer
rm -rf wuftpd
rm -rf shell
rm -rf custom
rm -rf link
rm -rf export-test
rm -rf filemin
rm -rf flashterm
rm -rf ftelnet
rm -rf tunnel
rm -rf file
rm -rf cpan
rm -rf htaccess-htpasswd
rm -rf shellinabox
rm -rf ssh
rm -rf ssh2
rm -rf updown
rm -rf vnc