line0=Opcje konfigurowalne,11
wait=Domy�lny tryb oczekiwania na kopi� zapasow�,1,1-Czekaj na zako�czenie,0-Uruchom w tle
apply=Automatycznie stosowa� konfiguracj� mened�era?,1,1-Tak,0-Nie
groupmode=Pobiera� informacje o grupie w�z��w z,1,webmin-Modu�u Indeksu Serwer�w AdFreeZonea,oc-Mened�era bazy danych OCM,-Nik�d
showdirs=Zawsze wy�wietla� zdalnych mened�er�w?,1,1-Tak,0-Nie
line1=Ustawienia bazy danych Bacula,11
driver=Typ bazy danych,1,Pg-PostgreSQL,mysql-MySQL,SQLite-SQLite
user=U�ytkownik do zalogowania w bazie danych,0
pass=Has�o do zalogowania,0
host=Serwer bazy danych Bacula,3,Ten system
db=Baza danych lub plik zawieraj�cy informacj� Bacula,0
line2=Ustawienia pliku,11
bacula_dir=Katalog konfiguracyjny Bacula,0
bextract=Pe�na �cie�ka do komendy <tt>bextract</tt>,0
bls=Pe�na �cie�ka do komendy <tt>bls</tt>,0
btape=Pe�na �cie�ka do komendy <tt>btape</tt>,0
init_start=Uruchom i zatrzymaj Bacula u�ywaj�c,1,1-Skrypt�w Init,0-polecenia <tt>bacula</tt>
