line1=Opcje konfiguracyjne,11
resolve=Rozwi�zywa� znalezione adresy serwer�w,1,1-Tak,0-Nie
scan_time=Czas oczekiwania na wynik skanowania,0
listen=Skanuj serwery na porcie UDP,3,Takim samym jak ten system
display_mode=Wy�wietl serwery jako,1,1-Tabela,0-Ikony
sort_mode=Sortuj serwery wed�ug,4,4-Adres�w IP,1-Nazwy host�w,2-Opis�w,3-OS,5-Grup,0-Kolejno�ci utworzenia
show_status=Wy�wietl stan serwer�w,1,1-Tak,0-Nie
show_ip=Zawsze wy�wietlaj adres i port na stronie g��wnej,1,1-Tak,0-Nie
deflink=Domy�lny tryb logowania,4,0-Normalne po��czenie do serwera,1-Loguj przez AdFreeZone,2-Loguj po klikni�ciu na ikon�,3-Loguj z samym loginem i has�em
deffast=Domy�lny tryb RPC,1,1-Szybki,2-Automatyczny,0-Wolny
auto_type=Domy�lny typ systemu,14,show_deftype
skipips=Adresy IP lub nazwy host�w systemu nie zosta�y wykryte,9,50,5,\t
skipifaces=Interfejs sieci nie zosta� wykryty,0
max_servers=Poka� formularz wyszukiwania, je�li liczba serwer�w przekracza,0
line2=Ustawienia systemowe,11
groups_dir=Grupy katalogu klastra MSC,0
