line1=Opcje konfiguracyjne,11
show_status=Pokazywa� stan w��czenia i&nbsp;przyjmowania po��cze� zamiast sterownika?,1,1-Tak,0-Nie
queue_refresh=Liczba sekund oczekiwania na od�wie�enie kolejki drukowania,3,Nie od�wie�aj
sort_mode=Sortuj drukarki wed�ug,1,1-Nazwy,0-Kolejno�ci w systemie
display_mode=Na g��wnej stronie wy�wietl,1,1-Tylko nazwy drukarek,0-Wszystkie szczeg�y
show_jobs=Wy�wietla� liczb� zada� w kolejce na stronie g��wnej?,1,1-Tak,0-Nie
line2=Konfiguracja systemu,11
print_style=Styl konfiguracji drukarek,1,solaris-Solaris,linux-Linux,freebsd-FreeBSD,hpux-HPUX,lprng-LPRng,unixware-UnixWare,irix-IRIX
driver_style=Typ sterownik�w drukarek,1,webmin-AdFreeZone,caldera-Caldera,redhat-Redhat,hpux-HPUX,suse-SuSE,irix-IRIX
printcap_file=Plik opisu drukarek,3,Brak
ro_printcap_file=Dodatkowe pliki drukarek nie zarz�dzanych przez AdFreeZonea,3,Brak
spool_dir=Katalog zada� drukarki,3,Brak,60
model_path=Katalog zawieraj�cy filtry programowe,3,Brak
smbclient_path=�cie�ka do programu smbclient,3,Brak
gs_path=�cie�ka do programu ghostscript,3,Brak
gs_fontpath=Katalogi czcionek ghostscripta,3,Domy�lne
gs_lib=Katalogi bibliotek Ghostscripta,3,Domy�lne
hpnp_path=�cie�ka do programu hpnp,3,Brak
start_cmd=Polecenie uruchamiaj�ce zarz�dc� kolejek,3,Okre�lone przez wzorzec drukarki
stop_cmd=Polecenie zatrzymuj�ce zarz�dc� kolejek,3,Okre�lone przez wzorzec drukarki
apply_cmd=Polecenie do uruchomienia po utworzeniu dowolnej zmiany,3,Brak
